# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9182a013474a7f240d163a34646ccfa1079f60f75cef9afec05a2db783046ac02acef43ed9dacadb1fb2618597d31d0a107dfe878a43b51a47e8223ef8dff1cc

test:
  secret_key_base: 5f0df959fa44589015842ed0df86a837bde0e52b4c191cb6c098bd1d586c72fe1e8bb691cbd0e94f408eb127b8aa8be57e417748dd6c02f5f8a1d9b7d2072f49

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
